plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: "chore"
          scope: "deps"
          release: "patch"

  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - "pyproject.toml"
          from: "^version = \".*\""
          to: "version = \"${nextRelease.version}\""
          results:
            - file: "pyproject.toml"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - "service.yaml"
          from: "eu.gcr.io/development-170812/timescale-api:.*"
          to: "eu.gcr.io/development-170812/timescale-api:${nextRelease.version}"
          results:
            - file: "service.yaml"
              hasChanged: true


branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"

tagFormat: "${version}"