apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: garden-server
  labels:
    cloud.googleapis.com/location: europe-west1

spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - image: gcr.io/garden-server-381815/garden-server:1.8.1  # x-release-please-version
            command:
            - ./manage.py
            - populate_weather
            env:
              - name: DJANGO_SETTINGS_MODULE
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: DJANGO_SETTINGS_MODULE
              - name: CSRF_TRUSTED_ORIGINS
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: CSRF_TRUSTED_ORIGINS
              - name: ALLOWED_HOST
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: ALLOWED_HOST
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: SECRET_KEY
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: DATABASE_URL
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
          maxRetries: 0
          timeoutSeconds: '600'
          serviceAccountName: 400668159616-compute@developer.gserviceaccount.com
