# Generated by Django 4.2 on 2023-04-16 19:13

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="Weather",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time", models.DateTimeField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("temperature", models.FloatField()),
                ("apparent_temperate", models.FloatField()),
                ("rain", models.FloatField()),
                ("cloud_cover", models.FloatField()),
                ("weather_code", models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="weather",
            constraint=models.UniqueConstraint(
                fields=("date_time", "location"), name="unique_weather_for_location_time"
            ),
        ),
    ]
