# Generated by Django 4.2 on 2023-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_rename_apparent_temperate_weather_apparent_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="is_forecast",
            field=models.BooleanField(default=False),
        ),
    ]
