# Generated by Django 4.2 on 2023-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_weather_created_weather_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="weather_code",
            field=models.FloatField(
                choices=[
                    (0, "Clear sky"),
                    (1, "Mainly clear, partly cloudy, and overcast"),
                    (2, "Mainly clear, partly cloudy, and overcast"),
                    (3, "Mainly clear, partly cloudy, and overcast"),
                    (45, "Fog and depositing rime fog"),
                    (48, "Fog and depositing rime fog"),
                    (51, "Drizzle: Light, moderate, and dense intensity"),
                    (53, "Drizzle: Light, moderate, and dense intensity"),
                    (55, "Drizzle: Light, moderate, and dense intensity"),
                    (56, "Freezing Drizzle: Light and dense intensity"),
                    (57, "Freezing Drizzle: Light and dense intensity"),
                    (61, "Rain: Slight, moderate and heavy intensity"),
                    (63, "Rain: Slight, moderate and heavy intensity"),
                    (65, "Rain: Slight, moderate and heavy intensity"),
                    (66, "Freezing Rain: Light and heavy intensity"),
                    (67, "Freezing Rain: Light and heavy intensity"),
                    (71, "Snow fall: Slight, moderate, and heavy intensity"),
                    (73, "Snow fall: Slight, moderate, and heavy intensity"),
                    (75, "Snow fall: Slight, moderate, and heavy intensity"),
                    (77, "Snow grains"),
                    (80, "Rain showers: Slight, moderate, and violent"),
                    (81, "Rain showers: Slight, moderate, and violent"),
                    (82, "Rain showers: Slight, moderate, and violent"),
                    (85, "Snow showers slight and heavy"),
                    (86, "Snow showers slight and heavy"),
                    (95, "Thunderstorm: Slight or moderate"),
                    (96, "Thunderstorm with slight and heavy hail"),
                    (99, "Thunderstorm with slight and heavy hail"),
                ]
            ),
        ),
    ]
