# Generated by Django 4.2 on 2023-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0008_weather_weather_wea_date_ti_accf53_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="weather_code",
            field=models.FloatField(
                choices=[
                    (0, "Clear sky"),
                    (1, "Mainly clear"),
                    (2, "Mainly partly cloudy"),
                    (3, "Mainly overcast"),
                    (45, "Fog"),
                    (48, "Depositing rime fog"),
                    (51, "Light Drizzle"),
                    (53, "Moderate Drizzle"),
                    (55, "Heavy Drizzle"),
                    (56, "Light Freezing Drizzle"),
                    (57, "Heavy Freezing Drizzle"),
                    (61, "Slight Rain"),
                    (63, "Moderate Rain"),
                    (65, "Heavy Rain"),
                    (66, "Light Freezing Rain"),
                    (67, "Heavy Freezing Rain"),
                    (71, "Light Snow fall"),
                    (73, "Moderate Snow fall"),
                    (75, "Heavy Snow fall"),
                    (77, "Snow grains"),
                    (80, "Slight Rain showers"),
                    (81, "Moderate Rain showers"),
                    (82, "Heavy Rain showers"),
                    (85, "Slight Snow showers"),
                    (86, "Heavy Snow showers"),
                    (95, "Thunderstorm"),
                    (96, "Thunderstorm with slight hail"),
                    (99, "Thunderstorm with heavy hail"),
                ]
            ),
        ),
    ]
