# Generated by Django 4.0.5 on 2022-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('abstract', models.TextField(blank=True)),
                ('content', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock())], use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('content', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('content', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
    ]
