# Generated by Django 4.0.6 on 2022-07-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, help_text='The URL for the Twitter page')),
                ('linkedin_url', models.URLField(blank=True, help_text='The URL for the LinkedIn page')),
                ('github_url', models.URLField(blank=True, help_text='The URL for the Github page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
