# Generated by Django 4.0.4 on 2022-06-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("indoor", models.BooleanField()),
                ("slug", models.SlugField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("unit", models.CharField(max_length=50)),
                ("colour", models.CharField(max_length=50)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="data_types", to="plants.plant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("data", models.FloatField()),
                ("data_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plants.datatype")),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plant_data", to="plants.plant"
                    ),
                ),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
        migrations.AddConstraint(
            model_name="plant",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_plant_name_for_user"),
        ),
    ]
