# Generated by Django 4.1.5 on 2023-02-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_rename_datatype_sensor_alter_datapoint_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="data_type",
            new_name="sensor",
        ),
        migrations.AlterField(
            model_name="sensor",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="plants.plant",
            ),
        ),
    ]
