# Generated by Django 4.1.7 on 2023-03-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0005_rename_data_type_datapoint_sensor_alter_sensor_plant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="sensor",
            name="new_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plants.sensorunit",
            ),
        ),
    ]
