# Generated by Django 4.1.7 on 2023-03-26 14:18

from django.db import migrations


def move_old_units(apps, schema):
    SensorUnit = apps.get_model("plants", "SensorUnit")
    Sensor = apps.get_model("plants", "Sensor")

    for unit in Sensor.objects.values("unit").distinct():
        sensor_unit = SensorUnit(name=unit)
        sensor_unit.save()

    for sensor in Sensor.objects.all():
        sensor.new_unit = SensorUnit.objects.get(unit=sensor.unit)
        sensor.save()


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0006_sensorunit_sensor_new_unit"),
    ]

    operations = [migrations.RunPython(move_old_units)]
