# Generated by Django 4.1.7 on 2023-03-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0007_new_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="unit",
        ),
        migrations.RenameField(
            model_name="sensor",
            old_name="new_unit",
            new_name="unit"
        ),
    ]
