# Generated by Django 4.2 on 2023-04-11 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0008_remove_sensor_new_unit_alter_sensor_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapoint",
            options={},
        ),
    ]
