# Generated by Django 4.2 on 2023-05-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zones", "0001_initial"),
        ("plants", "0009_alter_datapoint_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="zone",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="zones.zone"),
        ),
    ]
