name: CI
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/testing.txt
      - name: Lint
        run: |
          black --line-length 120 --exclude '/migrations/' --check apps project
          isort --check-only --diff apps project -l 120