name: CI
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/testing.txt
      - name: Black Lint
        run: black --line-length 120 --exclude '/migrations/' --check apps project

      - name: Isort Lint
        run: isort --check-only --diff apps project -l 120

      - name: Migrations Check
        run: python manage.py makemigrations --check --dry-run

      - name: Template Check
        run: python manage.py validate_templates --verbosity 0

      - name: Django Tests
        env:
          DJANGO_SETTINGS_MODULE: 'project.settings.testing'
        run:
          coverage run --include="apps/*" ./manage.py test --noinput . apps
