name: Release
on:
  push:
    branches:
      - main

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}