name: Release
on:
  push:
    tags:
      - '*'

jobs:
  gcr-push:
      name: Push to GCR
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ubuntu packages
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          libgdal26
      - name: Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: ${{ secrets.GCLOUD_IMAGE_NAME }}
          image_tag: latest,${{ github.ref_name }}
          dockerfile: ./Dockerfile

  migrate:
      name: Migrate Database
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install Ubuntu packages
          run: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            libgdal26
        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.11'
        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
        - name: Install dependencies
          run: |
            poetry install

        - name: Migrate
          run: poetry run ./manage.py migrate --settings="project.settings.production"
          env:
            DJANGO_DATABASE_NAME: ${{ secrets.DJANGO_DATABASE_NAME }}
            DJANGO_DATABASE_USER: ${{ secrets.DJANGO_DATABASE_USER }}
            DJANGO_DATABASE_PASSWORD: ${{ secrets.DJANGO_DATABASE_PASSWORD }}
            DJANGO_DATABASE_HOST: ${{ secrets.DJANGO_DATABASE_HOST }}
            DJANGO_SETTINGS_MODULE: project.settings.production
            ALLOWED_HOSTS: 127.0.0.1
            CSRF_TRUSTED_ORIGINS: http://127.0.0.1

  deploy-web-service:
    name: Deploy Web Service
    runs-on: ubuntu-20.04
    needs: [migrate, gcr-push]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ubuntu packages
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          libgdal26
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - id: deploy
        name: Deploy to GCR
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          region: europe-west1
          metadata: ./services/web_service.yaml

  deploy-weather-cron:
    name: Deploy Weather Cron Job
    runs-on: ubuntu-20.04
    needs: [migrate, gcr-push]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ubuntu packages
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          libgdal26
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - id: deploy
        name: Deploy to GCR
        run: gcloud run jobs replace ./services/weather_service.yaml